[package]
name = "plist2json"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
clap = { version = "4.5.4", features = ["derive"] }
color-eyre = "0.6.3"
plist = "1.6.1"
serde_json = "1.0.115"
